import 'server-only';
import Anthropic from '@anthropic-ai/sdk';
import type { AnomalyResult } from './anomaly';
import type { MarketSnapshotJson } from './types';

// ============================================================
// Claude market-intelligence summary (spec §9).
// Server-only: uses ANTHROPIC_API_KEY. Returns 2–3 sentences. On any failure
// the caller falls back to a deterministic string — AI never blocks the UI.
//
// Labelled in the UI as "AI-assisted (rules-based)" for anomaly detection;
// this narrative summary is generated by Claude and labelled as such.
// ============================================================

const MODEL = 'claude-opus-4-8';

export interface SummaryInput {
  bids: { amount: number; transitDays: number | null }[];
  anomalies: Pick<AnomalyResult, 'severity'>[];
  marketSnapshot: MarketSnapshotJson | null;
}

export async function generateTenderSummary(input: SummaryInput): Promise<string> {
  const apiKey = process.env.ANTHROPIC_API_KEY;
  if (!apiKey) throw new Error('ANTHROPIC_API_KEY not set');

  const client = new Anthropic({ apiKey });

  const amounts = input.bids.map((b) => b.amount).sort((a, b) => a - b);
  const flagged = input.anomalies.filter((a) => a.severity === 'flagged').length;
  const review = input.anomalies.filter((a) => a.severity === 'review').length;

  const facts = {
    bid_count: input.bids.length,
    lowest: amounts[0] ?? null,
    highest: amounts[amounts.length - 1] ?? null,
    spread_pct:
      amounts.length > 1 && amounts[0] > 0
        ? Number((((amounts[amounts.length - 1] - amounts[0]) / amounts[0]) * 100).toFixed(1))
        : 0,
    flagged,
    review,
    bdi: input.marketSnapshot?.value ?? null,
    bdi_stale: input.marketSnapshot?.stale ?? false,
  };

  const message = await client.messages.create({
    model: MODEL,
    max_tokens: 220,
    system:
      'You are a freight procurement analyst. Given tender facts, write 2-3 concise, factual sentences for a procurement manager. Do not invent numbers. Mention the bid spread, any flagged/review bids, and how the Baltic Dry Index context bears on freight cost. Plain text, no markdown.',
    messages: [{ role: 'user', content: `Tender facts (JSON):\n${JSON.stringify(facts, null, 2)}` }],
  });

  const text = message.content
    .filter((c): c is Anthropic.TextBlock => c.type === 'text')
    .map((c) => c.text)
    .join(' ')
    .trim();

  if (!text) throw new Error('Empty AI response');
  return text;
}
